cmf_routing:
    chain:
        # FIXME: make a PR so support routers_by_tag: { name: routing.chained_router, priority: 200 }
        routers_by_id:
            router.default: 200
            cmf_routing.dynamic_router: 100
    dynamic:
        enabled: true
        route_provider_service_id: contao.routing.provider
        controllers_by_type:
            page_regular:   contao.controllers.frontend:regularPageAction
            page_forward:   contao.controllers.redirect:redirectAction
            page_redirect:  contao.controllers.redirect:redirectAction
            page_error_403: contao.controllers.frontend:accessDeniedAction
            page_error_404: contao.controllers.frontend:notFoundAction
            page_root:      contao.controllers.redirect:redirectAction
