services:
    # CMF routing
    contao.routing.candidates_strategy:
        class: Symfony\Cmf\Component\Routing\Candidates\Candidates
        arguments:
            - ['de', 'en'] # FIXME: static locales

    contao.routing.provider:
        alias: contao.routing.chain_provider

    contao.routing.chain_provider:
        class: Contao\CoreBundle\Routing\ChainedRouteProvider

    contao.routing.page_provider:
        class: Contao\CoreBundle\Routing\PageRouteProvider
        arguments:
            - '@contao.routing.candidates_strategy'
            - '@event_dispatcher'
        tags:
            - { name: cmf_routing.provider, priority: 100 }

    contao.templating.static_urls:
        class: Contao\CoreBundle\Templating\StaticUrlProvider
        arguments:
            - '@request_stack'

    contao.templating.layout:
            class: Contao\CoreBundle\Templating\LayoutProvider
            factory: [Contao\CoreBundle\Templating\LayoutProvider, createFromMasterRequest]
            arguments:
                - '@request_stack'

    contao.templating.page:
            class: Contao\CoreBundle\Templating\PageRenderer
            arguments:
                - '@contao.templating.static_urls'

    # Event subscribers
    contao.subscriber.create_page_routes:
        class: Contao\CoreBundle\Routing\CreatePageRoutesSubscriber
        tags:
            - { name: kernel.event_subscriber }

    # Event listener
    contao.listener.maintenance_mode:
            class: Contao\CoreBundle\EventListener\MaintenanceModeListener
            tags:
                - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 254 }

    contao.listener.output_from_cache:
        class: Contao\CoreBundle\EventListener\OutputFromCacheListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 200 }

    contao.listener.toggle_view:
        class: Contao\CoreBundle\EventListener\ToggleViewListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 150 }

    contao.listener.parameter_filter:
        class: Contao\CoreBundle\EventListener\ParameterFilterListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 31 }

    contao.listener.add_to_search_index:
        class: Contao\CoreBundle\EventListener\AddToSearchIndexListener
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }
