services:
    contao.listener.toggle_view:
        class: Contao\CoreBundle\EventListener\ToggleViewListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 150 }

    contao.listener.parameter_filter:
        class: Contao\CoreBundle\EventListener\ParameterFilterListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 31 }

    contao.listener.output_from_cache:
        class: Contao\CoreBundle\EventListener\OutputFromCacheListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 200 }

    contao.listener.add_to_search_index:
        class: Contao\CoreBundle\EventListener\AddToSearchIndexListener
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }
