<?php

namespace Contao\CoreBundle\Doctrine\Mapping;

use Contao\CoreBundle\Framework\ContaoFrameworkInterface;
use Doctrine\Common\Persistence\Mapping\RuntimeReflectionService;

class ContaoModelRuntimeReflectionService extends RuntimeReflectionService
{
    /**
     * @var ContaoFrameworkInterface
     */
    private $framework;

    /**
     * Constructor.
     *
     * @param ContaoFrameworkInterface $framework
     */
    public function __construct(ContaoFrameworkInterface $framework)
    {
        $this->framework = $framework;
    }

    public function getAccessibleProperty($class, $property)
    {
        $this->framework->initialize();

        if (is_a($class, '\Contao\Model', true)) {
            return null;
        }

        return parent::getAccessibleProperty($class, $property); // TODO: Change the autogenerated stub
    }
}
